export const GET_MOVIES = "GET_MOVIES"

export const ADD_MOVIES = "ADD_MOVIES"
export const ADD_MOVIES_REJECTED = "ADD_MOVIES_REJECTED"
export const ADD_MOVIES_FULFILLED = "ADD_MOVIES_FULFILLED"
export const ADD_MOVIES_PENDING = "ADD_MOVIES_PENDING"


export const GET_MOVIES_WITHID = "GET_MOVIES_WITHID"
export const GET_MOVIES_WITHID_REJECTED = "GET_MOVIES_WITHID_REJECTED"
export const GET_MOVIES_WITHID_FULFILLED = "GET_MOVIES_WITHID_FULFILLED"
export const GET_MOVIES_WITHID_PENDING = "GET_MOVIES_WITHID_PENDING"

export const UPDATE_MOVIES = "UPDATE_MOVIES"
export const UPDATE_MOVIES_REJECTED = "UPDATE_MOVIES_REJECTED"
export const UPDATE_MOVIES_FULFILLED = "UPDATE_MOVIES_FULFILLED"
export const UPDATE_MOVIES_PENDING = "UPDATE_MOVIES_PENDING"